config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

resources :categories, except: :show
resources :products, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    has_many :products, dependent: :restrict_with_exception
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/product.rb
class Product < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
    }

    ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
    }

    has_one_attached :photo
    
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true
    belongs_to :category
    belongs_to :user, default: -> { Current.user }

    def owner?
        user_id == Current.user.id
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: true,
        format: {
        with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
        message: :invalid
        }
    validates :username, presence: true, uniqueness: true,
        length: { in: 3..15 },
        format: {
            with: /\A[a-z0-9A-Z]+\z/,
            message: :invalid
        }
    validates :password, length: { minimum: 6 }
    has_many :products, dependent: :destroy 

    before_save :downcase_attributes

    private

    def downcase_attributes
        self.username = username.downcase
        self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include Authorization
  include Language
  include Pagy::Backend  
  
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController
    skip_before_action :protect_pages

    def new
    end

    def create
        @user = User.find_by("email = :login OR username = :login", { login: params[:login] })

        if @user&.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to products_path, notice: t('.created')
        else
            redirect_to new_session_path, alert: t('.failed')
        end
    end

    def destroy
        session.delete(:user_id)
    
        redirect_to products_path, notice: t('.destroyed')
    end
end

app/controllers/authentication/users_controller.rb
class Authentication::UsersController < ApplicationController
    skip_before_action :protect_pages

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to products_path, notice: t('.created')
        else
            render :new, status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :username, :password)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize!

  # GET /categories or /categories.json
  def index
    @categories = Category.all.order(name: :asc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    category
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_url, notice: t('.created')
    else
      render :new, status: :unprocessable_entity 
    end
  end


  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    if category.update(category_params)
        redirect_to categories_url, notice: t('.updated') 
    else
        render :edit, status: :unprocessable_entity 
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: t('.destroyed') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/concerns/authentication.rb
module Authentication
    extend ActiveSupport::Concern

    included do
    before_action :set_current_user
    before_action :protect_pages

    private

    def set_current_user
        Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def protect_pages
        redirect_to new_session_path, alert: t('common.not_logged_in') unless Current.user
    end
    end
end

app/controllers/concerns/authorization.rb
module Authorization
    extend ActiveSupport::Concern

    included do
        class NotAuthorizedError < StandardError; end

        rescue_from NotAuthorizedError do
            redirect_to products_path, alert: t('common.not_authorized')
        end

        private

        def authorize! record = nil
            is_allowed = "#{controller_name.singularize}Policy".classify.constantize.new(record).send(action_name)
            raise NotAuthorizedError unless is_allowed
        end
    end
end

app/controllers/concerns/language.rb
module Language
    extend ActiveSupport::Concern

    included do
        around_action :switch_locale

        private

        def switch_locale(&action)
            I18n.with_locale(locale_from_header, &action)
        end

        def locale_from_header
            request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController 
    skip_before_action :protect_pages, only: [:index, :show]

    def index
        @categories = Category.order(name: :asc).load_async
        @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)
    end

    def show
        product
    end

    def new
        @product = Product.new
    end

    def create 
        @product = Product.new(products_params)
        if @product.save
            redirect_to products_path, notice: t('.created')
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        authorize! product
    end

    def update
        authorize! product
        if product.update(products_params)
            redirect_to products_path, notice: t('.updated')
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        authorize! product
        product.destroy
        redirect_to products_path, notice: t('.destroyed'), status: :see_other
    end

    private
    def products_params
        params.require(:product).permit(:title, :description, :price, :photo, :category_id)
    end

    def product_params_index
        params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page)
    end

    def product
        @product = Product.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/authentication/users/new.html.erb
<%= form_with(model: @user) do |form| %>
    <% @user.errors.full_messages.each do |error| %>
        <div>
            <%= error %>
        </div>
    <% end %>

    <div>
        <%= form.label :email %>
        <%= form.email_field :email, required: true %>
    </div>

    <div>
        <%= form.label :username %>
        <%= form.text_field :username, required: true %>
    </div>

    <div>
        <%= form.label :password %>
        <%= form.password_field :password, required: true %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <%= category.name %>
    <%= link_to t('.edit'), edit_category_path(category)%>
<%=link_to t('.delete'), category_path(category), data: {turbo_method: :delete ,turbo_confirm: t('common.confirm')} %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
        <%= error %>
        <br />
  <%end%>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>
<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>
<%= link_to t('.new'), new_category_path %>
<%= render partial: "category", collection: @categories %>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>
<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %> | <%= t('meta_title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash'%>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do %>
    <%= category.name %>
<% end %>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
    <% @product.errors.full_messages.each do |error| %>
        <%= error %>
        <br />
    <%end%>
    <div>
        <%=form.label :title%>
        <%=form.text_field :title%>
    </div>

    <div>
        <%=form.label :description%>
        <%=form.text_area :description%>
    </div>

    <div>
        <%=form.label :price%>
        <%=form.number_field :price%>
    </div>

    <div>
        <%=form.label :photo%>
        <%=form.file_field :photo%>
    </div>

    <div>
        <%= form.label :category_id %>
        <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
    </div>

    <%=form.submit%>
<%end%>

app/views/products/_product.html.erb
<%=link_to product_path(product), class: 'product', 'data-turbo-frame': '_top' do%>
    <%= image_tag product.photo, width: 150 if product.photo.attached?%>
    <h3><%= product.title %></h3>

<%end%>
<h4><%=product.description%></h4>
<p><%=product.price%>$</p>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>
    <h2><%= t('.title') %></h2>

    <%= form_with url: products_path, method: :get do |form| %>
        <%= form.text_field :query_text, placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
        <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price] %>
        <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price] %>
        <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| [t(".#{order}"), order] }, params[:order_by]), {}, { onChange: 'this.form.requestSubmit()' } %>
    <% end %>

    <%= link_to t('.all'), products_path %>

    <%= render partial: "category", collection: @categories %>
    <br />
    <br />
    <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products' do %>
        <%= render partial: 'product', collection: @products %>
        <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
    <% end %>
<% end %>

app/views/products/new.html.erb
<h2><%= t('.title') %></h2>
<%= render 'form' %>

app/views/products/show.html.erb
<h1 class='title'><%=@product.title%></h1>
<%= image_tag @product.photo, width: 200 if @product.photo.attached? %>

<p class='description'><%=@product.description%></p>
<span class='price'> <%=@product.price%>$ </span>

<br>
<%= link_to t('.edit'), edit_product_path(@product) if @product.owner? %>
<%=link_to t('.delete'), product_path(@product), data: {
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
    } if @product.owner? %>

app/views/shared/_flash.html.erb
<%= alert %>


<%= notice %>

app/views/shared/_header.html.erb
<%= link_to products_path do%>
<h1><%= t('app_name') %></h1>
<% end %>

<%= link_to t('.add'), new_product_path if Current.user %>
<%= link_to t('.categories'), categories_path if Current.user&.admin? %>
<%= link_to t('.login'), new_session_path unless Current.user %>
<%= link_to t('.register'), new_user_path unless Current.user %>
<%= link_to t('.logout'), session_path(Current.user.id), data: {
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
} if Current.user %>